#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# write-env.sh — materialize forge/.env.local from environment variables.
#
# Contains NO secret itself. It copies whatever SF_*/JFL_* env vars are present
# at runtime (set them in your Claude Code web environment, CI secrets, or your
# shell) into the gitignored forge/.env.local that Forge + the integration layer
# read. This lets you configure the key WITHOUT a local clone and WITHOUT ever
# committing it.
#
# Safe no-op when SF_LLM_KEY is unset (leaves any existing file alone). When the
# base/model are not given, they are inferred from the key prefix:
#   nvapi-*  -> NVIDIA gateway, z-ai/glm-5.1
#   sk-ant-* -> Anthropic,      claude-haiku-4-5
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/forge/.env.local"

if [ -z "${SF_LLM_KEY:-}" ]; then
  echo "[write-env] SF_LLM_KEY not set in the environment — leaving forge/.env.local unchanged." >&2
  exit 0
fi

base="${SF_LLM_BASE:-}"
case "$SF_LLM_KEY" in
  nvapi-*)  base="${base:-https://integrate.api.nvidia.com}"; ddef="z-ai/glm-5.1";     cdef="z-ai/glm-5.1" ;;
  sk-ant-*) base="${base:-https://api.anthropic.com}";        ddef="claude-haiku-4-5"; cdef="claude-haiku-4-5" ;;
  *)        base="${base:-https://api.anthropic.com}";        ddef="claude-haiku-4-5"; cdef="claude-haiku-4-5" ;;
esac

umask 077  # secret file: owner read/write only
cat > "$ENV_FILE" <<EOF
# Generated by scripts/write-env.sh from environment variables — gitignored.
# Do NOT commit. Change the env vars (Claude Code environment / CI secrets), not this file.
SF_LLM_KEY=${SF_LLM_KEY}
SF_LLM_BASE=${base}
SF_DISTILL_MODEL=${SF_DISTILL_MODEL:-$ddef}
SF_CLASSIFY_MODEL=${SF_CLASSIFY_MODEL:-$cdef}
SF_MIN_BUCKET_SIZE=${SF_MIN_BUCKET_SIZE:-1}
JFL_PORT=${JFL_PORT:-8099}
JFL_DEFAULT_KEY=${JFL_DEFAULT_KEY:-jfl-local-dev-key}
JFL_AUTODISTILL=${JFL_AUTODISTILL:-1}
EOF
chmod 600 "$ENV_FILE"  # owner-only, even if the file pre-existed with looser perms

echo "[write-env] wrote $ENV_FILE (key from \$SF_LLM_KEY, base ${base})"
